services:
  todo-service:
    image: ankodd/golang-todo-service:latest
    ports:
      - "8080:8080"
      - "8082:8082"
    networks:
      - my-network
    container_name: todo-service

  prometheus:
    image: prom/prometheus:main
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my-network
    container_name: prometheus


networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16